all: argumentos.exe manejo_argumentos.exe
argumentos.exe: argumentos.c
	gcc -o argumentos.exe argumentos.c
manejo_argumentos.exe: manejo_argumentos.c
	gcc -o manejo_argumentos.exe manejo_argumentos.c
