all: error obtener_error recuperar_error recuperar_error_2

error: error.c
	${CC} -o $@ $<

obtener_error: obtener_error.c
	${CC} -o $@ $<

recuperar_error: recuperar_error.c
	${CC} -o $@ $<

recuperar_error_2: recuperar_error_2.c
	${CC} -o $@ $<

clean:
	rm -f error obtener_error recuperar_error recuperar_error_2
	rm -f *~
